import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar structure for Physical AI & Humanoid Robotics textbook
  textbookSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: ['introduction/index'],
      link: {
        type: 'doc',
        id: 'introduction/index',
      },
    },
    {
      type: 'category',
      label: 'Module 1: ROS 2 Fundamentals',
      items: [
        'module1-ros2-fundamentals/chapter1-ros2-basics',
        'module1-ros2-fundamentals/chapter2-ros2-navigation',
        'module1-ros2-fundamentals/chapter3-ros2-manipulation',
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Simulation with Gazebo/Unity',
      items: [
        'module2-simulation-gazebo-unity/chapter4-gazebo-simulation',
        'module2-simulation-gazebo-unity/chapter5-unity-simulation',
        'module2-simulation-gazebo-unity/chapter6-sim-environments',
      ],
    },
    {
      type: 'category',
      label: 'Module 3: Advanced Robotics with NVIDIA Isaac',
      items: [
        'module3-advanced-robotics-nvidia-isaac/chapter7-isaac-sdk',
        'module3-advanced-robotics-nvidia-isaac/chapter8-isaac-manipulation',
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA) Systems',
      items: [
        'module4-vla-systems/chapter9-vision-language',
        'module4-vla-systems/chapter10-action-systems',
      ],
    },
    {
      type: 'category',
      label: 'Resources',
      items: ['resources/index'],
    },
    {
      type: 'category',
      label: 'Conclusion',
      items: ['conclusion/index'],
      link: {
        type: 'doc',
        id: 'conclusion/index',
      },
    },
  ],
};

export default sidebars;
